spring:
  application:
    name: apiRestRestful
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apirestrestful?useTimezone=true&serverTimezone=UTC
    username: developer
    password: 1234567
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: false
